-- File: Incrementer.vhd
-- Generated by MyHDL 0.11.49
-- Date: Fri Dec 27 16:41:52 2024


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity Incrementer is
    port (
        input_signal: in unsigned(7 downto 0);
        output_signal: out unsigned(7 downto 0)
    );
end entity Incrementer;


architecture MyHDL of Incrementer is


function MYHDL2_add_one(
    value: in unsigned
    ) return integer is
begin
    return to_integer(value + 1);
end function MYHDL2_add_one;

begin





output_signal <= to_unsigned(MYHDL2_add_one(input_signal), 8);

end architecture MyHDL;
